### ISSUE TITLE
Error after using this on th095

### ISSUE THREAD

**Issue by Swifty819** [MisterMonstr/2hu_steam-exe_to_disc-exe#1]
When used on th095, the below error appears when trying to run the game:

![image](https://user-images.githubusercontent.com/10109838/177703582-069f012b-631d-4fce-baaf-4405bb568f7f.png)

**Comment by MisterMonstr** [comment]
I re-did th095's bspatch file. Used ZUN's 1.02a update on an original disc EXE, then made the patchfile with that. Tested and seems to be working fine on my end. Just pushed the new one. Let me know if this new one works for you!

**Comment by Swifty819** [comment]
Bingo! Full disclosure, I found something with 12.5 too, so another ticket will be coming.
